package VistaVendedor;

import VistaAdministrador.*;
import Clases.Producto;
import Clases.Usuario;
import DB.DB_SIMULATOR;
import javax.swing.table.DefaultTableModel;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JComboBox;

//for image:
import java.awt.*;
import java.awt.image.BufferedImage;
import java.net.URL;
import javax.crypto.SealedObject;
import javax.imageio.ImageIO;
import javax.swing.*;
import javax.swing.border.*;


public class GestionProductos extends javax.swing.JPanel {
    private DB_SIMULATOR database;
    private Usuario usuario;
    private Producto selectedProduct;
    
//    String[] categorias = {
//        "Todo",
//        "Laptop",
//        "Smartphone",
//        "Tablet",
//        "Monitor",
//        "Teclado",
//        "Mouse",
//        "Auriculares",
//        "Impresora",
//        "Router",
//        "Disco Duro",
//        "SSD",
//        "Memoria RAM",
//        "Smartwatch"
//    };
    /**
     * Creates new form GestionProductos
     */
    public GestionProductos(DB_SIMULATOR db, Usuario u) {
        initComponents();
        this.database = db;
        this.usuario = u;
        setupTable();
        //setupCategorias();
        updateTableData(database.getAllProducts()); 
    }

//    private void setupCategorias(){
//       categorias_box.removeAllItems();
//        for (String c : categorias) {
//            categorias_box.addItem(c);
//        }
//    }
    
    private void updateProductData(){
        label_nombre.setText(selectedProduct.getNombre());
        label_precio.setText("<html><b>Precio:</b> S/ " + selectedProduct.getPrecio() + "</html>");
        label_marca.setText("<html><b>Marca:</b> " + selectedProduct.getMarca() + "</html>");
        label_dimens.setText("<html><b>Dimensiones:</b> " + selectedProduct.getDimensiones() + "</html>");
        label_stock.setText("<html><b>Stock:</b> " + selectedProduct.getStock() + "</html>");
        label_especif.setText(selectedProduct.getEspecificaciones());
        
        label_total.setText("<html><br>Total:</br> S/ "+selectedProduct.getPrecio()+"</html>");
        
        input_cantidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, Integer.parseInt(selectedProduct.getStock()), 1));

        try {
            int m=15; 
            ImageRenderer.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(Color.BLACK,2),
                new EmptyBorder(m,m,m,m)
            ));
            ImageRenderer.setHorizontalAlignment(SwingConstants.CENTER);
            ImageRenderer.setVerticalAlignment(SwingConstants.CENTER);
            ImageRenderer.setText(null);

            BufferedImage img=ImageIO.read(new URL(selectedProduct.getImagen()));
            if(img==null) throw new Exception("Invalid image");

            Insets ins=ImageRenderer.getInsets();
            int aw=ImageRenderer.getWidth()-ins.left-ins.right, 
                ah=ImageRenderer.getHeight()-ins.top-ins.bottom,
                iw=img.getWidth(), ih=img.getHeight(), nw, nh;

            if((double)iw/ih > (double)aw/ah){ nw=aw; nh=nw*ih/iw; }
            else { nh=ah; nw=nh*iw/ih; }

            ImageRenderer.setIcon(new ImageIcon(img.getScaledInstance(nw,nh,Image.SCALE_SMOOTH)));
        } catch(Exception e){
            e.printStackTrace();
            ImageRenderer.setIcon(null);
            ImageRenderer.setText(null);
        }
    }
    
    private void setupTable() {
        //ProductsTable.removeColumn(ProductsTable.getColumnModel().getColumn(3));
        ProductsTable.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 1) {
                    int row = ProductsTable.getSelectedRow();
                    String productId = ProductsTable.getValueAt(row, 0).toString();
                    System.out.println("Product id: " + productId);
                    selectedProduct = database.getProductById(productId);
                    updateProductData();
                }
            }
        });
    
    }

    private void updateTableData(java.util.List<Producto> productos) {
        DefaultTableModel model = (DefaultTableModel) ProductsTable.getModel();

        model.setRowCount(0);
        for (Producto p : productos) {
            if (Integer.parseInt(p.getStock()) > 1) {
               model.addRow(new Object[]{p.getIdproducto(), p.getNombre(), p.getMarca(), p.getPrecio()});
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        barra_busqueda = new javax.swing.JTextField();
        buscar_button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ProductsTable = new javax.swing.JTable();
        categorias_box = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        ImageRenderer = new javax.swing.JLabel();
        label_nombre = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        label_dimens = new javax.swing.JLabel();
        label_marca = new javax.swing.JLabel();
        label_precio = new javax.swing.JLabel();
        label_especif = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        label_stock = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        label_total = new javax.swing.JLabel();
        input_cantidad = new javax.swing.JSpinner();

        jLabel1.setText("Buscador");

        buscar_button.setText("🔎");
        buscar_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscar_buttonMouseClicked(evt);
            }
        });
        buscar_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar_buttonActionPerformed(evt);
            }
        });

        ProductsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id", "Nombre", "Marca", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(ProductsTable);
        if (ProductsTable.getColumnModel().getColumnCount() > 0) {
            ProductsTable.getColumnModel().getColumn(0).setMinWidth(30);
            ProductsTable.getColumnModel().getColumn(0).setPreferredWidth(30);
            ProductsTable.getColumnModel().getColumn(0).setMaxWidth(30);
        }

        categorias_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todo", "Laptop", "Smartphone", "Tablet", "Monitor", "Mouse", "Teclado", "Auriculares", "Disco Duro", "SSD", "Memoria RAM", "Impresora", "Router", "Smartwatch" }));
        categorias_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categorias_boxActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        ImageRenderer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        label_nombre.setText("Nombre:");

        jLabel2.setText("<html><b>Especificaciones:</b></html>");

        label_dimens.setText("Dimensiones:");

        label_marca.setText("Marca:");

        label_precio.setText("Precio:");

        jButton1.setText("Agregar lista");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        label_stock.setText("Stock: ");

        jLabel3.setText("Cantidad:");

        label_total.setText("Total:");

        input_cantidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        input_cantidad.setToolTipText("");
        input_cantidad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                input_cantidadStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(input_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(label_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_marca)
                                    .addComponent(label_especif)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label_dimens)
                                    .addComponent(ImageRenderer, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label_stock)
                                    .addComponent(label_total))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_nombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ImageRenderer, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_precio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_dimens)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_stock)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_especif)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(3, 3, 3)
                .addComponent(input_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_total)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(categorias_box, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(barra_busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(buscar_button, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(categorias_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(barra_busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buscar_button, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buscar_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscar_buttonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_buscar_buttonMouseClicked

    private void buscar_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar_buttonActionPerformed

        System.out.println("Buscando: " + barra_busqueda.getText());
        updateTableData(database.getProductsByName(barra_busqueda.getText()));
        barra_busqueda.setText("");
    }//GEN-LAST:event_buscar_buttonActionPerformed

    private void categorias_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categorias_boxActionPerformed
        //System.out.println("Categoria seleccionada: " + categorias_box.getSelectedItem());
        updateTableData(database.getProductsByCategory(categorias_box.getSelectedItem().toString()));
    }//GEN-LAST:event_categorias_boxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void input_cantidadStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_input_cantidadStateChanged
        double total = Double.parseDouble(selectedProduct.getPrecio()) * Integer.parseInt(input_cantidad.getValue().toString());
        label_total.setText("<html><br>Total:</br> S/ "+total+"</html>");
    }//GEN-LAST:event_input_cantidadStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImageRenderer;
    private javax.swing.JTable ProductsTable;
    private javax.swing.JTextField barra_busqueda;
    private javax.swing.JButton buscar_button;
    private javax.swing.JComboBox<String> categorias_box;
    private javax.swing.JSpinner input_cantidad;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_dimens;
    private javax.swing.JLabel label_especif;
    private javax.swing.JLabel label_marca;
    private javax.swing.JLabel label_nombre;
    private javax.swing.JLabel label_precio;
    private javax.swing.JLabel label_stock;
    private javax.swing.JLabel label_total;
    // End of variables declaration//GEN-END:variables
}
